In [1]:
import csv

In [2]:
with open("/home/niraj/Downloads/winequality-red.csv",'r') as f:
    wines=list(csv.reader(f,delimiter=';'))

In [4]:
wines[:3]

AttributeError: 'list' object has no attribute 'format'

In [5]:
print(wines[:3])

[['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol', 'quality'], ['7.4', '0.7', '0', '1.9', '0.076', '11', '34', '0.9978', '3.51', '0.56', '9.4', '5'], ['7.8', '0.88', '0', '2.6', '0.098', '25', '67', '0.9968', '3.2', '0.68', '9.8', '5']]


In [11]:
import pandas as pd

df=pd.read_csv("/home/niraj/Downloads/winequality-red.csv",delimiter=';')

In [12]:
df[:3]

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5

In [14]:
qualities=[float(item[-1]) for item in wines[1:]]
sum(qualities)/len(qualities)

5.6360225140712945

In [15]:
import numpy as np
wines = np.array(wines[1:],dtype=np.float)

In [16]:
wines

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [17]:
wines.shape

(1599, 12)

In [19]:
empty_array = np.zeros((3,4))
empty_array

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [20]:
np.random.rand(3,4)

array([[ 0.19333197,  0.24493401,  0.29839314,  0.4776115 ],
       [ 0.30951299,  0.83546589,  0.3664843 ,  0.38223621],
       [ 0.37541976,  0.52444366,  0.15825641,  0.30840745]])

In [23]:
wines=np.genfromtxt("/home/niraj/Downloads/winequality-red.csv",delimiter=';',skip_header=1)

In [24]:
wines

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [25]:
wines[2,3]

2.2999999999999998

In [26]:
wines[0:3,3]

array([ 1.9,  2.6,  2.3])

In [27]:
wines[:3,3]

array([ 1.9,  2.6,  2.3])

In [28]:
wines[:,3]

array([ 1.9,  2.6,  2.3, ...,  2.3,  2. ,  3.6])

In [29]:
wines[3,:]

array([ 11.2  ,   0.28 ,   0.56 ,   1.9  ,   0.075,  17.   ,  60.   ,
         0.998,   3.16 ,   0.58 ,   9.8  ,   6.   ])

In [30]:
wines[3]

array([ 11.2  ,   0.28 ,   0.56 ,   1.9  ,   0.075,  17.   ,  60.   ,
         0.998,   3.16 ,   0.58 ,   9.8  ,   6.   ])

In [31]:
wines[:,:]

array([[  7.4  ,   0.7  ,   0.   , ...,   0.56 ,   9.4  ,   5.   ],
       [  7.8  ,   0.88 ,   0.   , ...,   0.68 ,   9.8  ,   5.   ],
       [  7.8  ,   0.76 ,   0.04 , ...,   0.65 ,   9.8  ,   5.   ],
       ..., 
       [  6.3  ,   0.51 ,   0.13 , ...,   0.75 ,  11.   ,   6.   ],
       [  5.9  ,   0.645,   0.12 , ...,   0.71 ,  10.2  ,   5.   ],
       [  6.   ,   0.31 ,   0.47 , ...,   0.66 ,  11.   ,   6.   ]])

In [32]:
wines[1,5]

25.0

In [33]:
wines[1,5]=10

In [34]:
wines[1,5]

10.0

In [35]:
wines[:,10]

array([  9.4,   9.8,   9.8, ...,  11. ,  10.2,  11. ])

In [36]:
wines[:,10]=50

In [37]:
wines[:,10]

array([ 50.,  50.,  50., ...,  50.,  50.,  50.])

In [38]:
third_wine=wines[3,:]

In [39]:
third_wine

array([ 11.2  ,   0.28 ,   0.56 ,   1.9  ,   0.075,  17.   ,  60.   ,
         0.998,   3.16 ,   0.58 ,  50.   ,   6.   ])

In [40]:
third_wine[1]

0.28000000000000003

In [41]:
np.random.rand(3)

array([ 0.21869782,  0.57978367,  0.75125907])

In [42]:

earnings = [
            [
                [500,505,490],
                [810,450,678],
                [234,897,430],
                [560,1023,640]
            ],
            [
                [600,605,490],
                [345,900,1000],
                [780,730,710],
                [670,540,324]
            ]
          ]

In [43]:
earnings=np.array(earnings)

In [44]:
earnings[0,0,0]

500

In [47]:
earnings.shape

(2, 4, 3)

In [48]:
earnings[:,0,0]

array([500, 600])

In [49]:
wines.dtype

dtype('float64')

In [51]:
wines.astype(int).dtype.name

'int64'

In [53]:
wines.astype(np.int32)

array([[ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       [ 7,  0,  0, ...,  0, 50,  5],
       ..., 
       [ 6,  0,  0, ...,  0, 50,  6],
       [ 5,  0,  0, ...,  0, 50,  5],
       [ 6,  0,  0, ...,  0, 50,  6]], dtype=int32)

In [55]:
wines[:,11]+=10

In [56]:
wines[:,11]

array([ 15.,  15.,  15., ...,  16.,  15.,  16.])

In [57]:
wines[:,11] * 2

array([ 30.,  30.,  30., ...,  32.,  30.,  32.])

In [58]:
wines[:,11]+wines[:,11]

array([ 30.,  30.,  30., ...,  32.,  30.,  32.])

In [59]:
wines[:,10] * wines[:,11]

array([ 750.,  750.,  750., ...,  800.,  750.,  800.])

In [60]:
wines.shape

(1599, 12)

In [61]:
wines * np.array([1,2])

ValueError: operands could not be broadcast together with shapes (1599,12) (2,) 

In [62]:
array_one = np.array(
    [
        [1,2],
        [3,4]
    ]
)
array_two = np.array([4,5])

array_one + array_two

array([[5, 7],
       [7, 9]])

In [67]:
wines+np.random.rand(12)

array([[  7.77495103,   1.3052524 ,   0.17757313, ...,   1.24122733,
         50.39104846,  15.86942604],
       [  8.17495103,   1.4852524 ,   0.17757313, ...,   1.36122733,
         50.39104846,  15.86942604],
       [  8.17495103,   1.3652524 ,   0.21757313, ...,   1.33122733,
         50.39104846,  15.86942604],
       ..., 
       [  6.67495103,   1.1152524 ,   0.30757313, ...,   1.43122733,
         50.39104846,  16.86942604],
       [  6.27495103,   1.2502524 ,   0.29757313, ...,   1.39122733,
         50.39104846,  15.86942604],
       [  6.37495103,   0.9152524 ,   0.64757313, ...,   1.34122733,
         50.39104846,  16.86942604]])

In [68]:
wines[:,11].sum()

25002.0

In [70]:
wines.sum(axis=0).shape

(12,)

In [72]:
wines.sum(axis=1).shape

(1599,)

In [73]:
wines[:,11]>5

array([ True,  True,  True, ...,  True,  True,  True], dtype=bool)

In [74]:
wines[:,11]==10

array([False, False, False, ..., False, False, False], dtype=bool)

In [75]:
high_quality = wines[:,11]>7

In [78]:
wines[high_quality,:][:3,:]

array([[  7.40000000e+00,   7.00000000e-01,   0.00000000e+00,
          1.90000000e+00,   7.60000000e-02,   1.10000000e+01,
          3.40000000e+01,   9.97800000e-01,   3.51000000e+00,
          5.60000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   8.80000000e-01,   0.00000000e+00,
          2.60000000e+00,   9.80000000e-02,   1.00000000e+01,
          6.70000000e+01,   9.96800000e-01,   3.20000000e+00,
          6.80000000e-01,   5.00000000e+01,   1.50000000e+01],
       [  7.80000000e+00,   7.60000000e-01,   4.00000000e-02,
          2.30000000e+00,   9.20000000e-02,   1.50000000e+01,
          5.40000000e+01,   9.97000000e-01,   3.26000000e+00,
          6.50000000e-01,   5.00000000e+01,   1.50000000e+01]])

In [83]:
high_quality_and_alcohol = (wines[:,10] > 10) & (wines[:,11] > 7)
wines[high_quality_and_alcohol,10:]=20

In [88]:
wines[high_quality_and_alcohol,10]=20

In [89]:
np.transpose(wines).shape

(12, 1599)

In [90]:
wines.ravel()

array([  7.4 ,   0.7 ,   0.  , ...,   0.66,  20.  ,  20.  ])

In [93]:
array_one = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]    
)
array_one.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [94]:
wines[1,:].reshape((2,6))

array([[  7.8   ,   0.88  ,   0.    ,   2.6   ,   0.098 ,  10.    ],
       [ 67.    ,   0.9968,   3.2   ,   0.68  ,  20.    ,  20.    ]])

In [96]:
white_wines = np.genfromtxt("/home/niraj/Downloads/winequality-white.csv",delimiter=';',skip_header=1)
white_wines.shape

(4898, 12)

In [97]:
all_wines = np.vstack((wines,white_wines))

In [99]:
all_wines.shape

(6497, 12)

In [101]:
np.concatenate((wines,white_wines),axis=0)

array([[  7.4 ,   0.7 ,   0.  , ...,   0.56,  20.  ,  20.  ],
       [  7.8 ,   0.88,   0.  , ...,   0.68,  20.  ,  20.  ],
       [  7.8 ,   0.76,   0.04, ...,   0.65,  20.  ,  20.  ],
       ..., 
       [  6.5 ,   0.24,   0.19, ...,   0.46,   9.4 ,   6.  ],
       [  5.5 ,   0.29,   0.3 , ...,   0.38,  12.8 ,   7.  ],
       [  6.  ,   0.21,   0.38, ...,   0.32,  11.8 ,   6.  ]])